import { RootProvider } from 'fumadocs-ui/provider/next';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} flex flex-col antialiased w-full min-h-screen`}
			>
				<ThemeProvider
					attribute={"class"}
					defaultTheme="light"
					disableTransitionOnChange
				>
					<RootProvider
						search={{
							enabled: false
						}}
					>
						{children}
					</RootProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
